name: expense

services:
  frontend:
    container_name: frontend
    pull_policy: always
    image: docker.io/poojasunil/frontend
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - common

  backend:
    container_name: backend
    image: docker.io/poojasunil/backend
    depends_on:
      - mysql
      - schema
    ports:
      - 8080:8080
    environment:
      DB_HOST: "mysql"
    networks:
      - common

  schema:
    container_name: schema-loader
    image: docker.io/poojasunil/schema-loader
    depends_on:
      - mysql
    environment:
      login_user: "root"
      login_password: "ExpenseApp@1"
      login_host: "mysql"
      app_repo: https://github.com/poojachiru04/expense-backend
      schema_file: /app/schema/backend.sql
    networks:
      - common

  mysql:
    container_name: mysql
    image: docker.io/mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "ExpenseApp@1"
    networks:
      - common

networks:
  common:
